# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33b9d944ca8c938d3771bd652a2a8c96592547f1818f8cb8f4d88754b4a1ab2e86750fcfc5c72ac4625356ff8f854dfb3f33850db8787f8542d74c901f4a48b1

test:
  secret_key_base: 2d3b658b0b7b6756e79bb32bd14db7bd2acac0b2859c11dd68e45758fc0198b924803dfc2b198204e80467720af2fe003ad37bd9cef5ac8e235e898a4e0c336e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
